# Default colors
[colors.primary]
background = '#0A0E14'
foreground = '#B3B1AD'

# Normal colors
[colors.normal]
black   = '#01060E'
red     = '#EA6C73'
green   = '#91B362'
yellow  = '#F9AF4F'
blue    = '#53BDFA'
magenta = '#FAE994'
cyan    = '#90E1C6'
white   = '#C7C7C7'

# Bright colors
[colors.bright]
black   = '#686868'
red     = '#F07178'
green   = '#C2D94C'
yellow  = '#FFB454'
blue    = '#59C2FF'
magenta = '#FFEE99'
cyan    = '#95E6CB'
white   = '#FFFFFF'

[cursor.style]
blinking = "always"
shape = "Block"

[font]
size = 13.0

[font.normal]
family = "Oxygen Mono"

[font.offset]
x = 0
y = 1

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Alt"

[window]
decorations = "Buttonless"
resize_increments = true
opacity = 0.8
blur = true

[env]
TERM = "xterm-256color"

[window.padding]
x = 20
y = 20
